package io.sugo.pio.ports;

/**
 * Superclass of behaviour classes that generate ports as needed.
 * 
 */
public interface PortExtender {

	/** Prefix for the names of the ports generated by this port extender. */
	public String getNamePrefix();

	/** Asks the port extender to generate at least this number of ports. */
	public void ensureMinimumNumberOfPorts(int minNumber);

}
